CREATE TYPE payment as ENUM (
    'Automatic',
    'Manual'
);

CREATE TABLE subscription (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subscription_name TEXT NOT NULL,
    subscription_price DECIMAL(12,2) NOT NULL,
    category payment NOT NULL,
    payment_date DATE NOT NULL
);