BEGIN;
CREATE TABLE subroom_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE subscription
    ADD COLUMN
        user_id INTEGER REFERENCES subroom_users(id)
        ON DELETE SET NULL;


COMMIT;